version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql-fase1
    restart: always
    environment:
      - MYSQL_DATABASE=oficina_fase1
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  mysql-volume:
    driver: local
