version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql-fase1
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=oficina_fase1
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
  api:
    build: .
    container_name: my-fastapi-fase1
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  mysql-volume:
    driver: local