apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
data:
  USER_DB: "lameque"
  HOST_DB: "<RDS-ENDPOINT>" 
  PORT_DB: "3306"
  DATABASE: "oficina_fase1"
  ALGORITHM: "HS256"
  EMAIL_TEST_USER: "teste@example.com"