apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oficina-api
  template:
    metadata:
      labels:
        app: oficina-api
    spec:
      containers:
        - name: api
          image: lamequesao/oficina-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: oficina-config
            - secretRef:
                name: oficina-secrets
