apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
data:
  EMAIL_HOST: "email-smtp.us-east-1.amazonaws.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "true"
  DEFAULT_FROM_EMAIL: "noreply@oficina-lameque.com"