apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
type: Opaque
data:
  PASSWORD_DB: bGFtZXF1ZTEyMw==  # base64('lameque123')
  SECRET_KEY: ZmMwNWM3NTcwYzM0NTk3ZGRiZjNhMDEwY2VkZDkyNDdkNTgzOWJkNzRiNmM1Zjk2Zjc3MGVkNGIwZjRkYzhmZg==  # base64(secret)
