# apiVersion: v1
# kind: Secret
# metadata:
#   name: api-secrets
#   namespace: oficina
# type: Opaque
# stringData:
#   DB_HOST: "<endpoint-do-rds>"
#   DB_PORT: "3306"
#   DB_USER: "lameque"
#   DB_PASSWORD: "lameque123"
#   DB_NAME: "oficina_fase1"

#   JWT_SECRET: "<MESMO_SEGREDO_DA_LAMBDA>"
#   JWT_ISSUER: "oficina-auth"
#   JWT_AUDIENCE: "oficina-api"

apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: oficina
type: Opaque
stringData:
  USER_DB: "fiapsoatdbuser"
  PASSWORD_DB: "Fiap2026macacoandadoDebike"
  HOST_DB: "fiap-challenge-db.csl02wc4kggn.us-east-1.rds.amazonaws.com"
  PORT_DB: "3306"
  DATABASE: "oficina_fase1"
  SECRET_KEY: "96a608225f6f7b165f339c5686ad046bfbbb721da012c4fc078b24f425b41a77"
  ALGORITHM: "HS256"
  JWT_ISSUER: "oficina-auth"
  JWT_AUDIENCE: "oficina-api"
