apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  USER_DB: YmFzZTY0LXVzZXJuYW1lCg==  # Base64 do username (ex.: root ou seu db_username do Terraform)
  PASSWORD_DB: YmFzZTY0LXBhc3N3b3JkCg==  # Base64 da senha (do db_password do Terraform)
  SECRET_KEY: YmFzZTY0LXNlY3JldC1rZXkK  # Base64 da sua SECRET_KEY
  EMAIL_TEST_USER: YmFzZTY0LWVtYWlsCg==  # Se necessário
  PASSWORD_TEST_USER: YmFzZTY0LXBhc3N3b3JkCg==  # Se necessário