apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: oficina-api
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
