name: CI/CD Pipeline

on:
  push:
    branches: [ main, teste-infra ]
  pull_request:
    branches: [ main, teste-infra ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumindo que requirements.txt existe

    # - name: Run tests
    #   run: |
    #     pytest  # Assumindo testes com pytest

    - name: Build Docker image
      run: docker build -t lamequesao/oficina-api:${{ github.sha }} .

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u lamequesao --password-stdin
        docker push lamequesao/oficina-api:${{ github.sha }}

    # - name: Login to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker image
    #   run: docker push ${{ secrets.DOCKER_USERNAME }}/oficina-api:${{ github.sha }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/teste-infra'
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # - name: Get RDS endpoint from Terraform
    #   id: terraform
    #   run: |
    #     cd terraform/
    #     RDS_ENDPOINT=$(terraform output -raw db_address)
    #     echo "RDS_ENDPOINT=$RDS_ENDPOINT" >> $GITHUB_ENV

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name oficina-fase2 --region us-east-1

    - name: Deploy to Kubernetes
      run: |
        sed -i "s|<RDS_ENDPOINT_DB>|${{ secrets.RDS_ENDPOINT }}|g" k8s/configmap.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/secrets.yaml
        kubectl apply -f k8s/deployment-api.yaml
        kubectl set image deployment/fastapi-app fastapi=lamequesao/oficina-api:${{ github.sha }}
        kubectl apply -f k8s/deployment-api.yaml
        kubectl apply -f k8s/service-api.yaml
        kubectl apply -f k8s/hpa.yaml

    - name: Deploy Database (managed by Terraform)
      run: |
        echo "Banco de dados gerenciado pelo Terraform (RDS). Nenhum deploy K8s necess√°rio."
